### PR TITLE
Switch to Maven

### PR DESCRIPTION
**Pull request by andreaTP**
WIP, for early feedback, still needs to verify the Kotlin exercises themselves.

If you have a little time to have a look @ErikSchierboom 🙏

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@andreaTP Holy smokes, this has cut the execution time in half! Where it used to take 23 seconds, it now takes about 11 seconds. It might be worth doing some additional testing, as there are also little tests here. But this is extremely exciting!

**Comment by andreaTP** [comment]
@ErikSchierboom there is a little issue I would love your guidance on.
In the Kotlin exercises both `junit` and `junit-jupiter` are used to run the tests, making them run both can be a little challenging and I do see an opportunity to standardize ... currently(at least) 87/92 `build.gradle.kts` are using `junit`, does it make sense to use it everywhere first?

**Comment by ErikSchierboom** [comment]
@andreaTP Likely. I don't know if there is something that `junit-jupiter` does that `junit` can't?

**Comment by andreaTP** [comment]
@ErikSchierboom here you have a comparison:
https://sormuras.github.io/blog/2018-09-13-junit-4-core-vs-jupiter-api.html

I noticed that the tests using jupiter are not available (I imagine they are excluded such as `annalyns`), and decided to move everything to junit: https://github.com/exercism/kotlin-test-runner/pull/34/commits/aa54c0e290569a736a3f06429cbdeaff02846ae2

I think this is good for a try 🙂

**Comment by ErikSchierboom** [comment]
> I noticed that the tests using jupiter are not available (I imagine they are excluded such as annalyns), and decided to move everything to junit: aa54c0e

Yes, they are both used in Concept Exercises, which haven't been enabled for Kotlin. So if you could send a PR to fix them there too at some point (no rush), that would be great. It doesn't delay this PR.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
