### PR TITLE
Add JUnit 5 support

### PR DESCRIPTION
**Pull request by ErwinOlie**
- Updated `bin/run.sh` and `examples/template/pom.xml` to support JUnit 5.
- Renamed existing tests under `/tests/` to add `-junit4` suffix.
- For each of the JUnit 4 test under `/tests/` a JUnit 5 variation is added.

### CODE REVIEW

**Comment by ErwinOlie** [comment]
@ErikSchierboom ready for review

**Review by ErikSchierboom — APPROVED** [review]
Great work! I love that you kept the existing test cases too as regression tests.

**Comment by ErikSchierboom** [comment]
@ErwinOlie is the next step to update the exercises in the `kotlin` repo to use JUnit 5?

**Comment by ErwinOlie** [comment]
@ErikSchierboom I don't think it's necessary for the performance improvement ideas. We can backwards support jUnit4 with junit5-vintage-api. However I haven't tried this yet

**Pull request merged**
