### PR TITLE
update to Gradle 8.4

### PR DESCRIPTION
**Pull request by ErwinOlie**
The changes in this PR consist of:
- replaced the deprecated _jcenter_ repository by _mavenCentral_
- added missing _settings.gradle.kts_ in all projects
- ran `gradle wrapper --gradle-version 8.4 --distribution-type bin`, this automatically updated the wrappers, wrapper properties and wrapper scripts to the latest versions. Note that most changed lines are because of this automated update.
- removed explicit `compile(kotlin("stdlib"))`. The latest gradle versions removed _compile_ which should be replaced by _implementation_ or _api_, but in the current version of the Gradle Kotlin plugin the stdlib is added automatically.
- updated Dockerfile to build with Gradle 8.4

This is my first PR here. Feedback is welcome :)

### CODE REVIEW

**Comment by iHiD** [comment]
(@ErikSchierboom See conversation at https://forum.exercism.org/t/kotlin-maintainer/7938/4)

**Comment by ErwinOlie** [comment]
Updated the description to tell what changed. I'll be adding a benchmark soon (but I don't expect any significant changes since maven is currently used for the test runs, if i'm not mistaken).

**Comment by ErwinOlie** [comment]
I time'd the `docker run` command in `run-tests-in-docker.sh` five times in a row on my own machine for both. Is that a good approach? I would like to give the performance problems a look as well later, can I use the same approach as a benchmark for that?

```
Before (Gradle 8.1.1 with some 6.0.1 wrappers)
real	0m54.529s
real	0m53.275s
real	0m53.502s
real	0m47.697s
real	0m54.221s
---
average 52.645s

After (Gradle 8.4.0)
real	0m57.295s
real	0m48.819s
real	0m57.015s
real	0m49.466s
real	0m49.706s
---
average 52.460s
```

I would argue that the little improvement can be seen as insignificant, especially since no change is expected.

**Review by ErikSchierboom — APPROVED** [review]
> I time'd the docker run command in run-tests-in-docker.sh five times in a row on my own machine for both. Is that a good approach? I would like to give the performance problems a look as well later, can I use the same approach as a benchmark for that?

That's because we only use Gradle to build the test runner asoftware, not to run the actual tests (which uses maven). I'm still happy to upgrade this.

**Pull request merged**
